[env]
TERM = "xterm-256color"

[font]
size = 18
offset.y = 5

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[colors.primary]
background = "#000000"

[window]
opacity = 0.9

