
background_opacity 1
modify_font cell_height 120%


# BEGIN_KITTY_THEME
# Dark Pastel
include current-theme.conf
# END_KITTY_THEME

font_size 26
font_family      JetBrainsMono Nerd Font Mono
bold_font        JetBrainsMono Nerd Font Mono Extra Bold
bold_italic_font JetBrainsMono Nerd Font Mono Extra Bold Italic
bold_italic_font auto

enable_audio_bell none
bell_on_tab none
